const  String baseUrl='https://test.bazarli.com/api/';
// Options options=Options(headers : { "app-id":"60bdbd22159b332fec7c83e6"} );
const String products="products/";
const String categories="getCategories/";
const String brands="suppliers/products/brands/";
const String attributes="attributes/";
const String families="families/";
const String customerLogin="customer/login";
const String customerRegister="customer/register";
